// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'
import { Document } from '@contentful/rich-text-types'

export interface IDhamFields {
  /** Dham Id */
  dhamId: string

  /** Name */
  name: string

  /** Season Type */
  seasonType?: string | undefined

  /** Duration */
  duration: string

  /** Location */
  location: string

  /** Best Time */
  bestTime: string

  /** Distance */
  distance: string

  /** Price */
  price: number

  /** Overview */
  overview: string

  /** Highlights */
  highlights: Document

  /** Short Itinerary */
  shortItinerary: Document

  /** Includes */
  includes: Document

  /** Excludes */
  excludes?: Document | undefined

  /** faq */
  faq?: Record<string, any> | undefined

  /** Cover Image */
  coverImage?: string | undefined

  /** Carousel Images */
  carouselImages?: Record<string, any> | undefined
}

export interface IDham extends Entry<IDhamFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'dham'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface INameFields {
  /** Trek Id */
  trekId: string

  /** Name */
  name: string

  /** Trek Season Type */
  trekSeasonType?: string | undefined

  /** Trek Duration */
  trekDuration: string

  /** Location */
  location: string

  /** Best Time */
  bestTime: string

  /** Difficulty */
  difficulty: string

  /** Distance */
  distance: string

  /** Price */
  price: number

  /** Overview */
  overview: string

  /** Highlights */
  highlights: Document

  /** Short Itinerary */
  shortItinerary: Document

  /** Includes */
  includes: Document

  /** Excludes */
  excludes?: Document | undefined

  /** faq */
  faq?: Record<string, any> | undefined

  /** Trek Cover Image */
  trekCoverImage?: string | undefined

  /** Treks Carousel Images */
  treksCarouselImages?: Record<string, any> | undefined
}

export interface IName extends Entry<INameFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'name'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE = 'dham' | 'name'

export type IEntry = IDham | IName

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
